export const INCREMENT_COUNTER= "INCREMENT_COUNTER";

export const DECREMENT_COUNTER= "DECREMENT_COUNTER";

export const RESET_COUNTER= "RESET_COUNTER";

export const INCREMENT_ASYNC= "INCREMENT_ASYNC";

export const FETCH_DATA= "FETCH_DATA";

export const DATA_FETCHING= "DATA_FETCHING";

export const FETCH_SUCCESS= "FETCH_SUCCESS";

export const FETCH_ERROR= "FETCH_ERROR";